- hosts: wordpress
  become: yes
  vars:
    mysql_password_file: /tmp/mysql_pass
    mysql_root_password_file: /tmp/root_pass
  tasks:
    - name: Install dependencies
      apt:
        name:
          - docker.io
          - docker-compose
          - git
        state: present
        update_cache: yes

    - name: Clone WordPress repo
      git:
        repo: 'git@github.com:yourusername/your-wordpress-repo.git'
        dest: /home/debian/wordpress
        version: main

    - name: Generate MySQL password if missing
      command: openssl rand -base64 16
      register: mysql_password
      args:
        creates: "{{ mysql_password_file }}"
      changed_when: mysql_password.rc == 0
    - copy:
        dest: "{{ mysql_password_file }}"
        content: "{{ mysql_password.stdout }}"
      when: mysql_password.stdout is defined

    - name: Generate MySQL root password if missing
      command: openssl rand -base64 20
      register: mysql_root_password
      args:
        creates: "{{ mysql_root_password_file }}"
      changed_when: mysql_root_password.rc == 0
    - copy:
        dest: "{{ mysql_root_password_file }}"
        content: "{{ mysql_root_password.stdout }}"
      when: mysql_root_password.stdout is defined

    - name: Create .env file for Docker
      template:
        dest: /home/debian/wordpress/.env
        mode: '0600'
        src: env.j2

    - name: Start WordPress containers
      command: docker-compose up -d
      args:
        chdir: /home/debian/wordpress
